### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by herrhartmann** [anaggh/halfmoon#1]
@anaggh Footer vanishes after posting new Blog entries. I could reproduce it on two installations.

**Comment by anaggh** [comment]
Just released a new update - https://github.com/anaggh/halfmoon/archive/1.1.1.zip Could you please test and see if it fixes it?

**Comment by anaggh** [comment]
Fixed in 1.1.2 https://github.com/anaggh/halfmoon/archive/1.1.2.zip

**Comment by herrhartmann** [comment]
Thanks!
