### ISSUE TITLE
[See More...] Option to Home Page Posts to reduce post length.

### ISSUE THREAD

**Issue by Deepnerd** [anaggh/halfmoon#4]
If I post a new post and go to the home page, there is a hugely long post, like this. https://ibb.co/WcGKRpd
can you add the See More.. option to posts to reduce the post length? Thank you very much for your hard work!
And thanks for adding the feature that I requested.

**Comment by anaggh** [comment]
It already exists. Did you try this https://docs.bludit.com/en/content/add-a-read-more-link ?

**Comment by Deepnerd** [comment]
Ohhhh my god you are the best! Thank you a lot! You solved my issue! <3 waiting for more exciting updates!
